// Generated by AI, DO NOT EDIT MANUALLY
package main

import (
	"testing"
)

func TestSwapIntegers(t *testing.T) {
	a := 10
	b := 20
	originalAddrA := &a
	originalAddrB := &b

	swap(&a, &b)

	if a != 20 {
		t.Errorf("expected a to be 20, got %d", a)
	}
	if b != 10 {
		t.Errorf("expected b to be 10, got %d", b)
	}

	if &a != originalAddrA {
		t.Errorf("address of a changed after swap")
	}
	if &b != originalAddrB {
		t.Errorf("address of b changed after swap")
	}
}

func TestSwapStrings(t *testing.T) {
	a := "hello"
	b := "world"

	swap(&a, &b)

	if a != "world" {
		t.Errorf("expected a to be 'world', got %s", a)
	}
	if b != "hello" {
		t.Errorf("expected b to be 'hello', got %s", b)
	}
}

func TestSwapFloats(t *testing.T) {
	a := 3.14
	b := 2.71

	swap(&a, &b)

	if a != 2.71 {
		t.Errorf("expected a to be 2.71, got %f", a)
	}
	if b != 3.14 {
		t.Errorf("expected b to be 3.14, got %f", b)
	}
}

func TestSwapStructs(t *testing.T) {
	type Person struct {
		Name string
		Age  int
	}
	a := Person{Name: "Alice", Age: 30}
	b := Person{Name: "Bob", Age: 25}

	swap(&a, &b)

	if a.Name != "Bob" || a.Age != 25 {
		t.Errorf("expected a to be {Bob 25}, got %+v", a)
	}
	if b.Name != "Alice" || b.Age != 30 {
		t.Errorf("expected b to be {Alice 30}, got %+v", b)
	}
}

func TestSwapSameVariable(t *testing.T) {
	a := 42

	swap(&a, &a)

	if a != 42 {
		t.Errorf("expected a to remain 42, got %d", a)
	}
}

func TestSwapPanicOnNonPointerFirstArg(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when first argument is not a pointer")
		}
		if r != "first argument must be a pointer" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	a := 10
	b := 20
	swap(a, b)
}

func TestSwapPanicOnNonPointerSecondArg(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when second argument is not a pointer")
		}
		if r != "second argument must be a pointer" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	a := "hello"
	b := "world"
	swap[any](&a, b)
}

func TestSwapPanicOnNilFirstPointer(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when first pointer is nil")
		}
		if r != "first argument is a nil pointer" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	var a *int = nil
	b := 20
	swap(a, &b)
}

func TestSwapPanicOnNilSecondPointer(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when second pointer is nil")
		}
		if r != "second argument is a nil pointer" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	a := 10
	var b *int = nil
	swap(&a, b)
}

func TestSwapPanicOnBothNilPointers(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when both pointers are nil")
		}
		if r != "first argument is a nil pointer" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	var a *int = nil
	var b *int = nil
	swap(a, b)
}

func TestSwapPanicOnDifferentTypes(t *testing.T) {
	defer func() {
		r := recover()
		if r == nil {
			t.Errorf("expected panic when pointers point to different types")
		}
		if r != "arguments are different types" {
			t.Errorf("unexpected panic message: %v", r)
		}
	}()

	a := 10
	b := "hello"
	swap[any](&a, &b)
}
